### ISSUE TITLE
CRDs can not be created with `apply`

### ISSUE THREAD

**Issue by fabiand** [kubernetes/apiextensions-apiserver#10]
The following `apply` call fails for me, but `creat`ing the same file works.

```
$ k apply -f /var/tmp/kubevirt-demo/kubevirt/manifests/vm-resource.yaml
error: unable to decode "/var/tmp/kubevirt-demo/kubevirt/manifests/vm-resource.yaml": no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1"
```

on a minikube:
```
$ minikube start --vm-driver kvm --network-plugin cni --iso-url https://storage.googleapis.com/minikube-builds/1846/minikube-testing.iso
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.

$ k api-versions
admissionregistration.k8s.io/v1alpha1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1beta1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2alpha1
batch/v1
batch/v2alpha1
certificates.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
rbac.authorization.k8s.io/v1beta1
settings.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

**Comment by deads2k** [comment]
@enisoc was this on the checklist you had for the integration tests?  I thought I remembered seeing it in test-cmd.

**Comment by enisoc** [comment]
This seems to be failing for the creation of the CRD itself, which should act like any other native resource. Is it possible that your `kubectl` is older than v1.7.0? This error seems to be coming from the client side, and it makes sense that `apply` would be trying to interpret things locally (to do strategic merge patch) whereas `create` can just pass through to the server.

@deads2k We do have tests for `kubectl apply` with CRD data, but we use `create` to install the actual CRD.

https://github.com/kubernetes/kubernetes/blob/2f00e6d72c9d58fe3edc3488a91948cf4bfcc6d9/hack/make-rules/test-cmd-util.sh#L1639-L1640

**Comment by fabiand** [comment]
Yes, thanks, that did the trick (client 1.7+):

```
$ kubectl apply -f /var/tmp/kubevirt-demo/kubevirt/manifests/vm-resource.yaml
customresourcedefinition "vms.kubevirt.io" configured
```
