### ISSUE TITLE
Vendor k8s.io/apiextensions-apiserver/pkg/features does not work

### ISSUE THREAD

**Issue by resouer** [kubernetes/apiextensions-apiserver#13]
cannot find package "k8s.io/apiextensions-apiserver/pkg/features"

**Comment by qianyong2005** [comment]
no features the package

**Comment by nikhita** [comment]
This repo is synced from https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiextensions-apiserver. The last sync was done 23 days ago. This should be fixed once the syncing is done.

Currently, the sync/publish bot is broken but a fix is underway: https://github.com/kubernetes/kubernetes/issues/51643.

**Comment by nikhita** [comment]
The syncing was done recently and `k8s.io/apiextensions-apiserver/pkg/features` exists now.

**Comment by nikhita** [comment]
Closing since this has been fixed and syncing is back in action with https://github.com/kubernetes/publishing-bot.

/close
