### ISSUE TITLE
Help running deepcopy-gen and or client-gen

### ISSUE THREAD

**Issue by srossross** [kubernetes/apiextensions-apiserver#15]
I am trying to adapt the `examples/client-go` by adding my own Custom Resource Type. When I change the name of the resource type from Example I get Deepcopy not supported errors. I think that I am supposed to run deepcopy-gen on the package to update `zz_generated.deepcopy.go` - but it is unclear how to do so.

**Comment by nikhita** [comment]
@srossross You'll need to use the code-generator: https://github.com/kubernetes/code-generator.

We are creating a sample controller example using the code-generator. Here is the PR for it: https://github.com/kubernetes/kubernetes/pull/52753. This should give a good idea! :)

**Comment by srossross** [comment]
👍 thanks

**Comment by nikhita** [comment]
@srossross This was published just today: https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/ - a blog post on how to use the code generator.

**Comment by srossross** [comment]
Thanks again.
