### ISSUE TITLE
Is there an example to show how to create an instance of CRD?

### ISSUE THREAD

**Issue by flyer103** [kubernetes/apiextensions-apiserver#16]
I have found an example of how to create a CRD resource and how to watch the events of a CRD resource from [this example](https://github.com/kubernetes/apiextensions-apiserver/tree/master/examples/client-go).

I want to create/update/delete an instance of a CRD resource, for example, I have created a CRD resource `OpCRD` and need to create/update/delete instances of `OpCRD`.

Are there some examples to show how to do this?

**Comment by nikhita** [comment]
@flyer103 We are updating the current example to depict a controller using code-generators (that is a best practice).

- Here is the PR for a sample controller: https://github.com/kubernetes/kubernetes/pull/52753. It is almost complete and you can use this as an example.

- About how to use the code-generator: https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/

The sample controller also has examples to [get](https://github.com/munnerz/kubernetes/blob/e9741c7b4373a7adfa863d49ecc5cf47abdae37d/staging/src/k8s.io/sample-controller/controller.go#L255), [update](https://github.com/munnerz/kubernetes/blob/e9741c7b4373a7adfa863d49ecc5cf47abdae37d/staging/src/k8s.io/sample-controller/controller.go#L334) the instance of your custom type. You can use a similar method for deleting as well.

Also, there are a bunch of tests [here](https://github.com/kubernetes/apiextensions-apiserver/blob/master/test/integration/basic_test.go) - they can be useful for understanding how to work with instances of your custom types.

**Comment by flyer103** [comment]
That's perfect and thanks! 😄
