### ISSUE TITLE
Is it invalid to create a CRD resource with multiple versions?

### ISSUE THREAD

**Issue by flyer103** [kubernetes/apiextensions-apiserver#17]
I could use `client-go` or CRD yaml file to create a CRD resource. But I need a resource with multiple versions in one cluster to do different things. I have tried but always got the error that the CRD resource has been created (using `client-go`) or field is immutable (using CRD yaml file).

So is it invalid to create a CRD resource with multiple versions?

**Comment by enisoc** [comment]
It's currently not possible to create a CRD with multiple versions. The main reason is that it would imply the need for code that knows how to convert between the versions, and CRD has no mechanism to inject such code.

Can you describe why you need multiple versions?

**Comment by munnerz** [comment]
If you are looking to implement multiple versions of a type, you should build out a custom API server (example: https://github.com/kubernetes/sample-apiserver)

As @enisoc says, you need to write conversions (or generate what conversions can be generated) between an *internal* API version, and your *external* (i.e. usable) versions. This is then used by the apimachinery to upgrade your types, and allow older clients to consume older versions of your types (i.e. backwards compatibility).

There is a good blog post on this by @sttts here: https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/

So the short answer is no, you can't with CRDs. If in the future there is some way to inject conversions into the API server, it might one day be possible. I'm not sure if there are any efforts to do this at the moment though.

**Comment by flyer103** [comment]
@enisoc Thanks for your reply and the following are the reasons:

* k8s is released very often and for [operator](https://coreos.com/blog/introducing-operators.html) developers or developers who use Helm to build apps, the changing of API version would increase the workload of maintaining apps. If a resource could have multiple versions in one cluster, it could make apps easier to run on different k8s clusters without changing API versions of resources.
* It's often to develop different API versions of a CRD resource on a k8s cluster. Though it's could be solved by changing APIGroup with the same kind, it becomes a different CRD resource but has the same semantic.

**Comment by flyer103** [comment]
@munnerz It's very detailed and thank you very much! 😄
I'll look into how to write an API server and using API Aggregation may help me solve the problem.
