### ISSUE TITLE
Could not create CRD on external cluster

### ISSUE THREAD

**Issue by R053NR07** [kubernetes/apiextensions-apiserver#19]
Hey,
I try to watch CRDs on multiple external clusters. For that purpose I created RESTClients (currently I do not have a clientset for those clusters) to watch the CRDs. 

So using the RESTClient to get, watch, ... is possible:
```
err = eRESTClient.Get().Resource(crv1.CRDPromPlural).Do().Into(&pl)
```
Works for me on an existiong CRD.

Now I wanted to create the CRDs automatically on new clusters if the CRD does not exist.

To do so I did following:
```
eClientset := apiextensionsclient.New(eRESTClient)

crd := &apiextensionsv1beta1.CustomResourceDefinition{
        ObjectMeta: metav1.ObjectMeta{
                Name: "tests.monitoring.io",
        },
        Spec: apiextensionsv1beta1.CustomResourceDefinitionSpec{
                Scope:   apiextensionsv1beta1.NamespaceScoped,
                Group:   "monitoring.io",
                Version: "v1",
                Names: apiextensionsv1beta1.CustomResourceDefinitionNames{
                        Kind:     "Test",
                        Plural:   "tests",
                        Singular: "test",
                },
        },
}
_, err = eClientset.Apiextensions().CustomResourceDefinitions().Create(crd)
```

But this does not work and following error appears:
```
the server could not find the requested resource (post customresourcedefinitions.monitoring.io)
```

Can somebody tell me if I need to do something special to my RESTClient to get that working, or why the clientset is not working in this case?

**Comment by R053NR07** [comment]
creating the clientset with "apiextensionsclient.NewForConfig(eRESTConfig)" works for me. But I still couldn't figure out why it's not working with the RESTClient.

**Comment by nikhita** [comment]
@R053NR07 Do you have an example code/repo for this? (to understand the issue better)

/priority awaiting-more-evidence

**Comment by R053NR07** [comment]
@nikhita Thanks for your reply. Sorry currently I don't have any public repo to show. We also restructured our code to use the rest config instead of a rest client, this works quite well for us.
