### ISSUE TITLE
unable to pull release-1.9 with dep

### ISSUE THREAD

**Issue by tylerauerbeck** [kubernetes/apiextensions-apiserver#22]
I'm currently trying to add k8s.io/apiextensions-apiservrer release-1.9 as a dependency to my project. However when I run the following:

`dep ensure -add k8s.io/apiextensions-apiserver@release-1.9`

The process just hangs and never completes. I've attempted this from multiple machines and networks to rule out the basic issues on my end. Is this expected behavior?

**Comment by munnerz** [comment]
Can you provide the output of `dep ensure -v -add k8s.io/apiextensions-apiserver@release-1.9`? Perhaps there is something going on under the hood that we're not seeing.

FWIW, I have managed to vendor release-1.9 as well as the version tags (kubernetes-1.9.1 etc.) just fine with dep: https://github.com/jetstack/cert-manager/blob/master/Gopkg.toml#L28

Also, what version of dep are you running?

**Comment by tylerauerbeck** [comment]
@munnerz 

dep output:
```
dep version
dep:
 version     : v0.3.2
 build date  : 2017-10-19
 git hash    : 8ddfc8a
 go version  : go1.9
 go compiler : gc
 platform    : linux/amd64
```

And the output of `dep ensure -v -add k8s.io/apiextensions-apiserver@release-1.9` can be seen [here](https://gist.github.com/tylerauerbeck/159e6bb385af04f0c5acd160c62122b6) . It looks like it gets hangs on 
```
(41)  ? attempt k8s.io/apiserver with 15 pkgs; 53 versions to try
(48) try k8s.io/apiserver@master
```

**Comment by sttts** [comment]
@tylerauerbeck until we ship a Gopkg.toml file inside of our libs, you **have to** specify the branches/tags of the dependencies as well. E.g. something like

```
dep ensure -v -add k8s.io/apiextensions-apiserver@release-1.9  k8s.io/apiserver@release-1.9 k8s.io/apimachinery@release-1.9 k8s.io/client-go@release-6.0
```

Then dep has to try considerably less revisions. Now you hit a combinatorial explosion because everything is unspecified. That takes time, a lot of time.

**Comment by nikhita** [comment]
>  until we ship a Gopkg.toml file inside of our libs

I believe this is being tracked in the main repo.

Closing. Please reopen if you still think there is an issue.
/close
