### ISSUE TITLE
use of vendored package not allowed

### ISSUE THREAD

**Issue by domcar** [kubernetes/apiextensions-apiserver#23]
Hi Guys,

maybe my problem is easy to solve but I can't get it working.
My goal is just to list/get CRD in my cluster (not created by me, already present).

I wrote the following code:
```
package main
import (
    "fmt"

    restext "k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest"
    ext "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1"
)
var k8sext, _ = newK8Sextclient()              // k8s client

func main() {
    fmt.Println("test")
}

func newK8Sextclient() (*ext.ApiextensionsV1beta1Client, error) {
    configext, err := restext.InClusterConfig()
    if err != nil { panic(err.Error()) }
    return ext.NewForConfig(configext)
}
```
but I get:
`main.go:5:5: use of vendored package not allowed`

What am I doing wrong?

Instead if I use the package `"k8s.io/client-go/rest"` I get this other error:
`./main.go:18:28: cannot use configext (type *"k8s.io/client-go/rest".Config) as type *"k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest".Config in argument to "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1".NewForConfig`

Thanks for your help

**Comment by nikhita** [comment]
@domcar try `restext "k8s.io/client-go/rest"` instead of `restext "k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest"`

**Comment by nikhita** [comment]
Ah, saw the edit now.

**Comment by codwu** [comment]
same problem +1

**Comment by lancelot1989** [comment]
same problem+1

I delete the vendor directory in the 'src/k8s.io/apiextensions-apiserver' to workaround this problem
