### ISSUE TITLE
CRD validation support references for core types

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/apiextensions-apiserver#27]
Common core types like ObjectMeta and PodSpec blow up the CRD validation into something unmanageable.  Openapi supports references to other specs.  We need to be able to reference core schema types from the validation so that CRDs aren't bloated with 100's of lines of boilerplate validation that obfuscates the important pieces defined by the user.

**Comment by nikhita** [comment]
https://github.com/kubernetes/kubernetes/issues/54579

**Comment by nikhita** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/54579.

/close
