### ISSUE TITLE
CRD TypeMeta empty for new objects

### ISSUE THREAD

**Issue by jakewins** [kubernetes/apiextensions-apiserver#29]
I think this is the same issue - except for CRDs, obviously - as https://github.com/kubernetes/client-go/issues/60

Basically:

- Create a CRD and a matching controller
- Set up the controller to print out the `TypeMeta` details of any objects passed to the `added` function hook
- The objects that show up are missing `TypeMeta`

This does not happen for subsequent changes - triggering the `updated` hook - it only occurs for the first added call. I've traced it back to the reflector on the controller side, I think the problem is present in the representation the controller get over the wire, but I'm not sure where to look on the REST API side.. 

Happy to help if someone has pointers for where to look on the server side. 

Here's a tiny project replicating the issue: 
https://github.com/jakewins/crd-missing-type

**Comment by enisoc** [comment]
The TypeMeta is often empty for core objects as well. For example, I ran into this problem with ReplicaSet objects. I was told that in general, you can't assume TypeMeta will always be filled in.

**Comment by nikhita** [comment]
@enisoc is right. :+1: 

See https://github.com/kubernetes/kubernetes/pull/59264#issuecomment-362575608 for more details.

**Comment by nikhita** [comment]
Also, related issue for core objects: https://github.com/kubernetes/client-go/issues/308

**Comment by nikhita** [comment]
> I've traced it back to the reflector on the controller side, I think the problem is present in the representation the controller get over the wire, but I'm not sure where to look on the REST API side..

This happens because we clear the gvk while decoding: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L256

**Comment by nikhita** [comment]
Fix in progress here: https://github.com/kubernetes/kubernetes/pull/63972

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/client-go/issues/413

**Comment by nikhita** [comment]
This was originally reported in https://github.com/kubernetes/kubernetes/issues/3030. Closing this in favor of it.

/close
