### ISSUE TITLE
Kubernetes 1.7 compatible branch?

### ISSUE THREAD

**Issue by ash2k** [kubernetes/apiextensions-apiserver#3]
How can I use CRD client from this repo with client-go release-4.0 (kubernetes 1.7) branch? They rely on different versions of apimachinery.

Related: https://github.com/kubernetes/client-go/issues/247

**Comment by ash2k** [comment]
Commit `be41f5093e2b05c7a0befe35b04b715eb325ab43` works for me - it's just before the commit that introduced `k8s.io/api` types.

**Comment by flyer103** [comment]
It's a headache to make  `kubernetes/client-go` `kubernetes/apimachinery` `kubernetes/apiextensions-apisever` work together 😢

**Comment by deads2k** [comment]
@caesarxuchao how about creating the branches that match kube like apimachinery?  1.6, 1.7, etc?

**Comment by caesarxuchao** [comment]
Creating a release-1.7 branch sounds good. Perhaps @sttts already have a PR out?

**Comment by pmorie** [comment]
+100 to tags/branches consistent with k8s releases.

**Comment by sttts** [comment]
> Creating a release-1.7 branch sounds good. Perhaps @sttts already have a PR out?

Of course: https://github.com/kubernetes/test-infra/pull/3559

Needs some review and testing love from @rmmh. It's pending for 16 days.

**Comment by sttts** [comment]
> +100 to tags

yes, please! @caesarxuchao do you see that in the bot or just documentation in the release process? If we can make it work via the bot, would be nicer of course.

**Comment by ConnorDoyle** [comment]
xref https://github.com/kubernetes/api/issues/5

**Comment by jinghzhu** [comment]
+1 to fix it.

I also face the k8s v1.7 compatible issue.

`client-go` release-4.0 still doesn't work with any tag of `apiextensions-apiserver `.

**Comment by nikhita** [comment]
We have tags in apiextensions-apiserver now.

**Comment by ash2k** [comment]
Both tags and branches.
