### ISSUE TITLE
Use as client go, got NotRegisteredErr

### ISSUE THREAD

**Issue by tedli** [kubernetes/apiextensions-apiserver#32]
I use github.com/kubeflow/tf-operator(v0.1.0), k8s.io/client-go(v5.0.0) in my project. The go dependencies was managed by `glide`, and it tells me tf-operator want apiextensions-apiserver with version kubernetes-1.8.4.

Codes built and ran. However, when run into

```golang
clientset.ApiextensionsV1beta1().CustomResourceDefinitions().Get("name", metav1.GetOptions{})
```

I got an error said "v1.GetOptions is not suitable for converting to \"meta.k8s.io/v1\".

Am I using those packages in mismatched versions? How can I solve the error. Thanks

**Comment by tedli** [comment]
finally I use a same tag (kubernetes-1.9.1) for `k8s.io/apiextensions-apiserver`, `k8s.io/apimachinery`, `k8s.io/api`, then works as expect.

**Comment by Gambler13** [comment]
@tedli 
Can you elaborate on this? I have exactly the same issue, but I can't solve it.

**Comment by tedli** [comment]
@Gambler13 
Hi, my problem was that I reused the `RESTClient` object.

My code was something like this:

```golang
import (
	"k8s.io/client-go/rest"
	"k8s.io/client-go/kubernetes"
	"k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
)

config := parseConfig()
client, _ := rest.RESTClientFor(config)
k8sClient := kubernetes.New(client)
apiExClient := clientset.New(client)
```

which was wrong.

If I use separated individual `RESTClient` object, this could be solved.

My code is now in this style:

```golang
config := parseConfig()
//client, _ := rest.RESTClientFor(config)
k8sClient, _ := kubernetes.NewForConfig(config)
apiExClient, _ := clientset.NewForConfig(config)
```
