### ISSUE TITLE
support subresources other than `status` and `scale`?

### ISSUE THREAD

**Issue by Jack47** [kubernetes/apiextensions-apiserver#33]
Seems CRD currently [doesn’t support sub resource other than `status` and `scale`](https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apiserver/customresource_discovery_controller.go#L139). 
So does this project have plan to support other sub resource? In Kubernetes there are a number of other subresources like /log, /exec, /bind. Although their semantics is much more special than `/status ` and `/scale`, but user needs apiextension-apiserver to allow implemting semantics.

**Comment by nikhita** [comment]
> So does this project have plan to support other sub resource?

No, I don't think there any plans to support custom subresources.

/cc @sttts @liggitt

**Comment by liggitt** [comment]
correct, that is not currently on the roadmap

/close
