### ISSUE TITLE
ListOptions with CRD

### ISSUE THREAD

**Issue by yaronha** [kubernetes/apiextensions-apiserver#4]
I tried to implement CRD List client function and specify ListOptions, followed the same pattern used by standard objects and it didn’t seem to work, is there a documented/working way to do this?
Im specifically interested in the LabelSelector option 

The following code didn’t work, and resulted in an error: 
     v1.ListOptions is not suitable for converting to "myorg.io/v1"

```golang
func (c *Client) List(namespace string, opts meta_v1.ListOptions) (*FunctionList, error) { 
       var result FunctionList
       err := c.restClient.Get().
              Namespace(namespace).Resource(c.getNamePlural()).
              VersionedParams(&opts, scheme.ParameterCodec).
              Do().Into(&result)
       return &result, err
}
```
it failed in the ParameterCodec.EncodeParameters() function  (called by VersionedParams() )

Yaron

**Comment by deads2k** [comment]
@sttts The generator should be including listoptions in the client scheme, right?

**Comment by sttts** [comment]
@yaronha `ListOptions` is registered for your api group in a line like this: https://github.com/kubernetes/kubernetes/blob/e2b50ac9b817dfb49c146b9423d1ee9a5da97cb2/staging/src/k8s.io/apiextensions-apiserver/examples/client-go/apis/cr/v1/register.go#L47. Can you verify you have that?

Is it a client-gen generated client or manually written? It would also help to see the full context. If you have a link to a branch on github, it would be awesome.

**Comment by yaronha** [comment]
@deads2k @sttts you can see the full code in https://github.com/yaronha/kube-crd
that was my CRD Tutorial, recently published in [TheNewStack](https://thenewstack.io/extend-kubernetes-1-7-custom-resources) 

just replace the List function in https://github.com/yaronha/kube-crd/client/client.go#L71  with the following:

```golang
func (f *crdclient) List(opts meta_v1.ListOptions) (*crd.ExampleList, error) {
	var result crd.ExampleList
	err := f.cl.Get().
		Namespace(f.ns).Resource(f.plural).
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().Into(&result)
	return &result, err
}
```

you can see the registration code (identical to your example) in:
https://github.com/yaronha/kube-crd/blob/master/crd/crd.go#L89

**Comment by yaronha** [comment]
@deads2k @sttts ok, i beleive i found the solution 

seems like i had to create a new ParameterCodec e.g.:
`myCodec = runtime.NewParameterCodec(scheme)`
and use myCodec in the list function (`VersionedParams(&opts, myCodec ).`)

**Comment by munnerz** [comment]
I've also put together an example repo showing how you can properly use Kubernetes generators to generate a Clientset, Informers, Listers and even conversions, deep copy functions etc (and save having to write all of this boilerplate yourself)

The example repo is here https://github.com/munnerz/k8s-api-pager-demo and I did a talk on it last night at the London CNCF meetup, the slides for which are here https://docs.google.com/presentation/d/1wrzYnd0Iqsir4Y2R8CTaH8_uTH9bm2a4WnXTyG8qtEU/edit

In the past I've tried to manually write my own Client implementation, or using the client-go 'dynamic' implementation, but always run into some form of issues (including the one you've run into above!)

**Comment by sttts** [comment]
@munnerz can you create an CRD example in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiextensions-apiserver/examples using client-gen? I am happy to review of course. I have the feeling that with https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiextensions-apiserver/examples/client-go we misguide people. You shouldn't use the rest client to work with CRDs.

**Comment by munnerz** [comment]
@sttts I'll try and find some time for that this week, sorry this slipped under my radar a couple of weeks ago!

**Comment by sttts** [comment]
@munnerz would be cool to have that in 1.8.

**Comment by armstrongli** [comment]
I have encountered this kind of issue, too. And I found that there're **2 different `api.Schema`**. One is `k8s.io/kubernetes/pkg/api`, the other is `k8s.io/client-go/pkg/api`. 
The service which use `client-go` won't be able to list/watch objects from shared informers with error `v1.ListOptions is not suitable for converting to ****`

The solution is to edit the `install.go` to register the object into both `api.Scheme`

**Comment by sttts** [comment]
@armstrongli neither of the two schemes should be relevant for 3rdparty work. What's you context? Something in the kubernetes tree? A CRD using client-go?

**Comment by armstrongli** [comment]
@sttts the way client-go i use client-go is special.
 - tge types are not defined in pkg/apis. they are defined in my own project. e.g. github.com/armstrongli/somesample/pkg/apis
 - the generated code is in kubernetes code, while the install/register is in my sample code.

there're no problems while not using client-go cause everything is registered in `kubernetes/api.Scheme`. 
And there're object issues while using client-go cause the install doesn't register itself into client-go Scheme

**Comment by nikhita** [comment]
https://github.com/kubernetes/sample-controller has been created now and depicts how to properly use generators (and hence properly use `ListOptions` as well).

**Comment by sttts** [comment]
Closing as we have the sample-controller now.
