### ISSUE TITLE
Separate repository or Go module for API types?

### ISSUE THREAD

**Issue by ash2k** [kubernetes/apiextensions-apiserver#57]
Currently lots of tools/libraries import this repo to use `CustomResourceDefinition`/etc types. With that, [lots of dependencies](https://github.com/kubernetes/apiextensions-apiserver/blob/master/go.mod) are imported. Most of them are not needed. This is problematic for many reasons - more code to download (slower builds), more code to scan for tools, etc.

Ideas:
- Move the API types into a separate repo like https://github.com/kubernetes/api
- Introduce a separate Go module in this repo. Maybe use workspace mode https://go.dev/doc/tutorial/workspaces

p.s. This may have been discussed already but I couldn't find any traces.

**Comment by tarvitz** [comment]
Sorry for bumping this thread up, but it really makes sense. For example, to build a simple demo webhook application that demonstrates admission behavior we require to "consume" good half of kubernetes itself.
