### ISSUE TITLE
Ensure CRD exists helper

### ISSUE THREAD

**Issue by ash2k** [kubernetes/apiextensions-apiserver#9]
There is a helper method in the example that creates a CRD and waits for it to be established. I have a similar method but a bit more sophisticated (uses a lister instead of a rest client, handles a number of edge cases like conflicts, can update CRD if it does not match). If there is interest I can submit a PR with it. Perhaps will need to make it more flexible first.

Existing code: https://github.com/kubernetes/apiextensions-apiserver/blob/master/examples/client-go/client/cr.go#L38

My version: https://github.com/atlassian/smith/blob/master/pkg/resources/crd_helpers.go#L38

**Comment by frankgreco** [comment]
@Gouthamve perhaps this will fix #5

**Comment by xh3b4sd** [comment]
Nice, we have something similar: https://github.com/giantswarm/operatorkit/blob/2804229e2bf865f72763ec1cf6f1d9dabb096665/client/k8scrdclient/k8scrdclient.go#L50. Would be cool to get this straight across the community. <3

**Comment by ash2k** [comment]
I think I'll be deploying the CRD as part of the other infrastructure objects necessary to run Smith, not as part of the application startup. It'll simplify things in the code quite a bit. But this functionality might still be useful in integration tests.

**Comment by nikhita** [comment]
@ash2k ping, are you still intending to work on the example? :)

/cc @sttts

**Comment by ash2k** [comment]
@nikhita Unfortunately I will not have any time to do this in the near future. We now create CRDs from yaml during "infrastructure" provisioning into the cluster. Our controllers no longer create/update CRDs, just assume they've been created already. However this method is still being used in integration tests where the CRD needs to be created programmatically for setup simplicity.

If nobody have desire/time to port this code or this code is not needed in this repo, then this issue can be closed.

**Comment by frankgreco** [comment]
@nikhita I can work on this.

**Comment by frankgreco** [comment]
@nikhita @sttts any updated on this issue: There is an open PR [here](https://github.com/kubernetes/kubernetes/pull/58715).
